# Generated by Django 4.0.1 on 2022-02-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('arlabel', models.TextField(blank=True, null=True)),
                ('enlabel', models.TextField(blank=True, null=True)),
                ('araliases', models.TextField(blank=True, null=True)),
                ('enaliases', models.TextField(blank=True, null=True)),
                ('ardescription', models.TextField(blank=True, null=True)),
                ('endescription', models.TextField(blank=True, null=True)),
                ('maincategory', models.TextField(blank=True, null=True)),
                ('arwiki', models.TextField(blank=True, null=True)),
                ('enwiki', models.TextField(blank=True, null=True)),
                ('arwikiquote', models.TextField(blank=True, null=True)),
                ('enwikiquote', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
